[package]
name = "keygen"
version = "2.0.0"
edition = "2021"

[[bin]]
name = "KeyGen"
path = "src/main.rs"

[dependencies]
kg_shared = { path = "../shared" }

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.52", features = [
    "Win32_Foundation",
    "Win32_System_Console",
    "Win32_System_Threading",
] }

[build-dependencies]
embed-resource = "2.4"
